packages:
  - "apps/*"
  - "apps/anyworker"
  - "apps/anyworker/gui"
  - "packages/*"

ignoreWorkspaceRootCheck: true

allowBuilds:
  esbuild: true
  lightningcss: true
  unrs-resolver: true
  msw: false
