/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DIndexRouteImport } from './routes/d/index'
import { Route as DPaperRouteImport } from './routes/d/paper'
import { Route as DStudioRouteImport } from './routes/d/studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DIndexRoute = DIndexRouteImport.update({
  id: '/d/',
  path: '/d/',
  getParentRoute: () => rootRouteImport,
} as any)
const DPaperRoute = DPaperRouteImport.update({
  id: '/d/paper',
  path: '/d/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const DStudioRoute = DStudioRouteImport.update({
  id: '/d/studio',
  path: '/d/studio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/d/paper': typeof DPaperRoute
  '/d/studio': typeof DStudioRoute
  '/d/': typeof DIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/d/paper': typeof DPaperRoute
  '/d/studio': typeof DStudioRoute
  '/d': typeof DIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/d/paper': typeof DPaperRoute
  '/d/studio': typeof DStudioRoute
  '/d/': typeof DIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/$' | '/d/paper' | '/d/studio' | '/d/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/d/paper' | '/d/studio' | '/d'
  id: '__root__' | '/' | '/api/$' | '/d/paper' | '/d/studio' | '/d/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DPaperRoute: typeof DPaperRoute
  DStudioRoute: typeof DStudioRoute
  DIndexRoute: typeof DIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/': {
      id: '/d/'
      path: '/d'
      fullPath: '/d/'
      preLoaderRoute: typeof DIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/paper': {
      id: '/d/paper'
      path: '/d/paper'
      fullPath: '/d/paper'
      preLoaderRoute: typeof DPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/studio': {
      id: '/d/studio'
      path: '/d/studio'
      fullPath: '/d/studio'
      preLoaderRoute: typeof DStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSplatRoute: ApiSplatRoute,
  DPaperRoute: DPaperRoute,
  DStudioRoute: DStudioRoute,
  DIndexRoute: DIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
